### ISSUE TITLE
Support for content negotiation as denoted in the standard is limited for some CDNs and http servers

### ISSUE THREAD

**Issue by markuskreusch** [oauth-wg/draft-ietf-oauth-status-list#168]
As described in https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-03.html#section-8.1 content negotiation using the accept header is used when requesting a status list / status list token. This is used to request different formats depending on the needs of the caller using a single URI for the status list.

This mechanism in general is valid and follows the http standards. Implementing this works well when an application server is used to serve the status lists.

Nevertheless in practice this causes problems in some scenarios. Several CDNs and services that provide caches of other HTTP resources do not implement the required functionality correctly.

For example [cloudflare, does explicitly ignore the accept header even if the vary http response header is used](https://developers.cloudflare.com/cache/concepts/cache-control/#other). Some other services offer this functionality tough, for example Amazon CloudFront.

In addition nginx can not easily handle content negotiation using the accept header correctly. Using the a map section together with the Accept header allows to choose different resources based on the requested content type. This is only working for single value Accept headers though. More complex header values as `Accept: application/statuslist+*;q=0.5,application/statuslist+cwt` can not easily be handled. The current state of the standard does not mention such option but does not forbid them either. Apache2 has https://httpd.apache.org/docs/current/content-negotiation.html, that could solve this. I did not evaluate that further.

So even though the mechanism is good and simple as is and follows http standards, it might be difficult to implement when using a CDN to scale serving the status list.

A possible solution would be to use distinct URIs to request the status list depending on the type (for example by appending extensions like jwt, cwt, json and cbor) instead of the request header. This seems to me as a workaround and a suboptimal solution though. As the specification as it is is totally valid IMHO it could as well been left as it is, which means the need for implementation of this functionality in the used components will arise and the usage of certain CDNs is not possible.

Related to #137 but addresses the request handling instead of response generation.

**Comment by paulbastian** [comment]
I think there are two reasons, why a failed negotiation my not be that significant:
- the unsigned option may probably be deleted, leaving us with 2 possible media types instead of 4
- from the ecosystem / context it may be clear whether JWT or CWT is expected

We could say that more complex header values as `Accept: application/statuslist+*;q=0.5,application/statuslist+cwt` are restricted?

**Comment by c2bo** [comment]
> A possible solution would be to use distinct URIs to request the status list depending on the type (for example by appending extensions like jwt, cwt, json and cbor) instead of the request header. This seems to me as a workaround and a suboptimal solution though. As the specification as it is is totally valid IMHO it could as well been left as it is, which means the need for implementation of this functionality in the used components will arise and the usage of certain CDNs is not possible.

This is kind of what I would expect for most cases in reality: A CBOR based Credential will likely reference to a status list that is only available in CWT form. The only solution to make this more explicit (and if we don't trust the header based approach) would be to make this explicit in the URI I guess?

**Comment by tplooker** [comment]
Discussed on editors call tonight, one possible recommendation we could make to implementations is that if you are representing the same underlying status list in both CWT and JWT forms, use distinct URIs for these two different status list representations e.g JWT -> https:example.com/statuslists/jwt/1 CWT -> https:example.com/statuslists/cwt/1. The only draw back I see to this approach is that in effect the reference to the status list that is put in the reference token effectively sets the content type of the returned status list, rather then making it subject to negotiation via the Accept header. I don't believe in practise is an issue because generally the same securing approach that is being used for the reference token should be used for the status list e.g SD-JWT reference token -> JWT status list.

**Comment by paulbastian** [comment]
Editors Call:
- decision at IETF 121 OAuth working group call to enforce HTTP Content-Type
- pending close
