### ISSUE TITLE
rename "referenced token" 

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/draft-ietf-oauth-status-list#26]
remaining issue from PR #20. 

alternatives are "referencing token".

**Comment by paulbastian** [comment]
Right now the diagram is a little confusing,
the upper arrow could point in both directions saying "References" or "Referencing"

**Comment by david-bakker** [comment]
> remaining issue from PR #20.
> 
> alternatives are "referencing token".

Hi, not sure this is the right place to raise the Referencing / Referenced Token discussion. In any case, a way out would perhaps be to drop the 'referencing' language, since indeed there are references between the two tokens both ways. So what about calling the Referenced Token the Listed Token? To me, that summarizes the relationship rather neatly: the Status List Token contains the list, a Listed Token (or, to be precise, the status of the Listed Token) is included in that list.

**Comment by paulbastian** [comment]
> > remaining issue from PR #20.
> > alternatives are "referencing token".
> 
> Hi, not sure this is the right place to raise the Referencing / Referenced Token discussion again. In any case, a way out would perhaps be to drop the 'referencing' language, since it seems unsolvable to me, as there are references between the two tokens both ways. So what about calling the Referenced Token the Listed Token instead? To me, that summarizes the relationship rather neatly: the Status List Token contains the status list, the status of a Listed Token is included in that list.

As the Status List draft is today also laying out a framework for other status mechanisms, the term "Referenced Token" seems better fitting as its quite neutral and would fit the Status Assertion draft as well, while "Listed Token" is very specific to Status List. We would hope that other Status mechanisms extending the proposed framework of this draft would adopt the same terminology. Looking at @peppelinux

**Comment by paulbastian** [comment]
The term seems established right now. Pending close if no further feedback

**Comment by david-bakker** [comment]
OK with me!
