### ISSUE TITLE
Should the JWT StatusList encoded 1-bit bytearray map to W3C StatusList 2021 bitstring?

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#68]
This came up twice now, so I think it makes sense to open this issue.

The StatusList2021 "counts" entries from right to left.

As our goal is to support multi-bit support for status types and bits are usually "counted" from right to left, we envision this more of a byte array, therefore counting indices and bits from right to left.

Therefore, the 1-bit strings do not match. Is this a problem? What are the consequences?

**Comment by brentzundel** [comment]
The status list under development in the W3C VCWG has evolved significantly since StatusList2021 was adopted. It now matches even more closely the work happening here.

I believe it would be incredibly valuable for the underlying status bytestrings in each approach to be identical. 

I have also [opened an issue](https://github.com/w3c/vc-bitstring-status-list/issues/93) in the related W3C repository to track this concern.

**Comment by bumblefudge** [comment]
as in, keep this issue open and remember to check for newest draft on the other side before shipping?

**Comment by dlongley** [comment]
> The StatusList2021 "counts" entries from right to left.
> 
> As our goal is to support multi-bit support for status types and bits are usually "counted" from right to left, we envision this more of a byte array, therefore counting indices and bits from right to left.

I might be misreading this. But I believe "entries" are counted from left to right, not right to left:

https://www.w3.org/TR/vc-status-list/#bitstring-encoding

This approach was chosen after some discussion and data collection around implementations, some of this can be seen in this PR or issues linked to it: https://github.com/w3c/vc-bitstring-status-list/pull/45

**Comment by dlongley** [comment]
> My initial read on this issue seems to confirm our choice that a byte array seems like a good approach to describe the content, because it is less ambiguous?

In terms of ambiguity, we've found that there are lots of ways people can get confused here. So plenty of text, descriptions, and pictures -- all internally consistent with one another -- are helpful. I don't think simply saying "byte array" (or "byte sequence" for that matter) instead of "bitstring" (or whatever else) is sufficient to alleviate misunderstanding -- and I'd even say the name choice won't move the needle very much.

**Comment by paulbastian** [comment]
Thats true, I was only stating my opinion and we should probably get more feedback on this.

**Comment by paulbastian** [comment]
Editors Call:
- we still believe to achieve our design goal of implementation easiness and simplicity, an approach using byte array instead of bitarray is better
- changes now would break many libraries for both standards
- so there is probably no solution to this
- pending close
